# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: swift-actions/setup-swift@2.0.0
      with:
        swift-version: "5.10"
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
